### PR TITLE
Add enum support.

### PR DESCRIPTION
**Pull request by aam**
Addresses #442.

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks very much!

**Comment by aam** [comment]
You're welcome. Happy to help.

**Comment by sethladd** [comment]
We'll let @guillermooo do the code review. :)

**Comment by guillermooo** [comment]
Looks great! Will try to merge this in soon.

@sethladd Is there a library to tokenize Dart code? That would let us test the syntax def in a more convenient way.

**Comment by sethladd** [comment]
Maybe the Analyzer?

cc @pquitslund

**Comment by pq** [comment]
For a dart-based tokenizer, the analyzer package is definitely your friend.  For Java, one could tease out the one in the intelliJ plugin since it's being actively maintained.  Happy to help with either!

**Comment by sethladd** [comment]
Thanks for the tip! Can you point us to the analyzer's API docs for the
tokenizer?

**Comment by pq** [comment]
Here's the relevant source:

**Comment by pq** [comment]
Hmmmm... I'm not seeing it in the generated docs (http://www.dartdocs.org/documentation/analyzer/0.22.4/index.html#analyzer).

Here's the relevant source though:
https://code.google.com/p/dart/source/browse/trunk/dart/pkg/analyzer/lib/src/generated/scanner.dart

Look for Scanner.

Alternatively, you could also use the highlighting service from the server though that may give you more than your need...  I'll let Brian chime in on that.

**Comment by guillermooo** [comment]
Thanks!

**Pull request merged**
